apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lms-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/Lms-app
    targetRevision: HEAD
    path: helm/lms-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
